version: "3"
services:
  ubuntu-server:
    build: ./src/dockerUbuntu/
    ports:
      - "80:80"
      - "2222:22"
    privileged: true

  ansible:
    build: ./src/dockerAnsible/
    volumes:
      - ./src:/usr/src
    working_dir: /usr/src
    command: ansible-playbook play.yml